// This file is generated by Slice Machine. Update with care!

import CustomerSlice from './CustomerSlice';
import Demo from './Demo';
import Hero from './Hero';
import LeftRightContent from './LeftRightContent';
import MultipleContentImageBlock from './MultipleContentImageBlock';
import NewSlice from './NewSlice';
import NewTestSlice from './NewTestSlice';
import Resources from './Resources';

export {
	CustomerSlice,
	Demo,
	Hero,
	LeftRightContent,
	MultipleContentImageBlock,
	NewSlice,
	NewTestSlice,
	Resources,
};

export const components = {
	customer_slice: CustomerSlice,
	demo: Demo,
	hero: Hero,
	left_right_content: LeftRightContent,
	multiple_content_image_block: MultipleContentImageBlock,
	new_slice: NewSlice,
	new_test_slice: NewTestSlice,
	resources: Resources,
};
